name: OCaml-CI
on: [push, pull_request]
jobs:
  macos_and_windows:
    strategy:
      matrix:
        operating-system: [macos-latest, windows-latest]
        ocaml-version: [4.12.0]
    runs-on: ${{ matrix.operating-system }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - name: Pinning Package
      run: opam pin add -yn uvarint.dev './' && opam pin add -yn multihash.dev './'
        && opam pin add -yn multihash-digestif.dev './' && opam pin add -yn multicodec.dev
        './' && opam pin add -yn multiaddr.dev './'
    - name: Packages
      run: opam depext -yt uvarint.dev multihash.dev multihash-digestif.dev multicodec.dev
        multiaddr.dev
    - name: Dependencies
      run: opam install -t -y . --deps-only
    - name: Building, Installing and Testing
      run: opam exec -- dune build @install @runtest
  debian_10_buster:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam@sha256:b92c270713f56b42b060dd88b6e33480e942124965f0656b5781a56e469b577d
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e 37ac8ae226969d6a789f1e5eb7e3dfdf2ec9a95a
        || git fetch origin master) && git reset -q --hard 37ac8ae226969d6a789f1e5eb7e3dfdf2ec9a95a
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - name: Cloning
      run: git clone --recursive https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - name: Pinning Packages
      run: opam pin add -yn uvarint.dev './' && opam pin add -yn multihash.dev './'
        && opam pin add -yn multihash-digestif.dev './' && opam pin add -yn multicodec.dev
        './' && opam pin add -yn multiaddr.dev './'
      working-directory: /home/opam/package
    - name: Installing external dependencies
      run: opam depext -yt uvarint.dev multihash.dev multihash-digestif.dev multicodec.dev
        multiaddr.dev
      working-directory: /home/opam/package
    - name: Installing dependencies
      run: opam install -t -y . --deps-only
      working-directory: /home/opam/package
    - name: Building, installing & testing
      run: opam exec -- dune build @install @runtest
      working-directory: /home/opam/package
  alpine_3_12:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam@sha256:3ade4e3abff09f25e24a7f538ca87b44dc1552c95c4b980bb44c576e182353c6
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e 37ac8ae226969d6a789f1e5eb7e3dfdf2ec9a95a
        || git fetch origin master) && git reset -q --hard 37ac8ae226969d6a789f1e5eb7e3dfdf2ec9a95a
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - name: Cloning
      run: git clone --recursive https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - name: Pinning Packages
      run: opam pin add -yn uvarint.dev './' && opam pin add -yn multihash.dev './'
        && opam pin add -yn multihash-digestif.dev './' && opam pin add -yn multicodec.dev
        './' && opam pin add -yn multiaddr.dev './'
      working-directory: /home/opam/package
    - name: Installing external dependencies
      run: opam depext -yt uvarint.dev multihash.dev multihash-digestif.dev multicodec.dev
        multiaddr.dev
      working-directory: /home/opam/package
    - name: Installing dependencies
      run: opam install -t -y . --deps-only
      working-directory: /home/opam/package
    - name: Building, installing & testing
      run: opam exec -- dune build @install @runtest
      working-directory: /home/opam/package
  ubuntu_20_04:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam@sha256:757706e8bf2d947ff24f097c8ce34fa6b00e652618211cfbf5c86ce18b7ea408
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e 37ac8ae226969d6a789f1e5eb7e3dfdf2ec9a95a
        || git fetch origin master) && git reset -q --hard 37ac8ae226969d6a789f1e5eb7e3dfdf2ec9a95a
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - name: Cloning
      run: git clone --recursive https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - name: Pinning Packages
      run: opam pin add -yn uvarint.dev './' && opam pin add -yn multihash.dev './'
        && opam pin add -yn multihash-digestif.dev './' && opam pin add -yn multicodec.dev
        './' && opam pin add -yn multiaddr.dev './'
      working-directory: /home/opam/package
    - name: Installing external dependencies
      run: opam depext -yt uvarint.dev multihash.dev multihash-digestif.dev multicodec.dev
        multiaddr.dev
      working-directory: /home/opam/package
    - name: Installing dependencies
      run: opam install -t -y . --deps-only
      working-directory: /home/opam/package
    - name: Building, installing & testing
      run: opam exec -- dune build @install @runtest
      working-directory: /home/opam/package
  ubuntu_18_04:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam@sha256:ebacfc4d2dbc3c6cb5b9bcc14e24297881f1d33db8b2b2d080e2d0839dab4561
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e 37ac8ae226969d6a789f1e5eb7e3dfdf2ec9a95a
        || git fetch origin master) && git reset -q --hard 37ac8ae226969d6a789f1e5eb7e3dfdf2ec9a95a
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - name: Cloning
      run: git clone --recursive https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - name: Pinning Packages
      run: opam pin add -yn uvarint.dev './' && opam pin add -yn multihash.dev './'
        && opam pin add -yn multihash-digestif.dev './' && opam pin add -yn multicodec.dev
        './' && opam pin add -yn multiaddr.dev './'
      working-directory: /home/opam/package
    - name: Installing external dependencies
      run: opam depext -yt uvarint.dev multihash.dev multihash-digestif.dev multicodec.dev
        multiaddr.dev
      working-directory: /home/opam/package
    - name: Installing dependencies
      run: opam install -t -y . --deps-only
      working-directory: /home/opam/package
    - name: Building, installing & testing
      run: opam exec -- dune build @install @runtest
      working-directory: /home/opam/package
  opensuse_15_2_leap:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam@sha256:10cd0783a451059ebfec3031f1c77472676483ff2844422f221137977429de97
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e 37ac8ae226969d6a789f1e5eb7e3dfdf2ec9a95a
        || git fetch origin master) && git reset -q --hard 37ac8ae226969d6a789f1e5eb7e3dfdf2ec9a95a
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - name: Cloning
      run: git clone --recursive https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - name: Pinning Packages
      run: opam pin add -yn uvarint.dev './' && opam pin add -yn multihash.dev './'
        && opam pin add -yn multihash-digestif.dev './' && opam pin add -yn multicodec.dev
        './' && opam pin add -yn multiaddr.dev './'
      working-directory: /home/opam/package
    - name: Installing external dependencies
      run: opam depext -yt uvarint.dev multihash.dev multihash-digestif.dev multicodec.dev
        multiaddr.dev
      working-directory: /home/opam/package
    - name: Installing dependencies
      run: opam install -t -y . --deps-only
      working-directory: /home/opam/package
    - name: Building, installing & testing
      run: opam exec -- dune build @install @runtest
      working-directory: /home/opam/package
  centos_8:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam@sha256:30d82620d220a6b9bf5d662fddbbdf487a4f43cf68d39f6442abbdf3e505a577
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e 37ac8ae226969d6a789f1e5eb7e3dfdf2ec9a95a
        || git fetch origin master) && git reset -q --hard 37ac8ae226969d6a789f1e5eb7e3dfdf2ec9a95a
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - name: Cloning
      run: git clone --recursive https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - name: Pinning Packages
      run: opam pin add -yn uvarint.dev './' && opam pin add -yn multihash.dev './'
        && opam pin add -yn multihash-digestif.dev './' && opam pin add -yn multicodec.dev
        './' && opam pin add -yn multiaddr.dev './'
      working-directory: /home/opam/package
    - name: Installing external dependencies
      run: opam depext -yt uvarint.dev multihash.dev multihash-digestif.dev multicodec.dev
        multiaddr.dev
      working-directory: /home/opam/package
    - name: Installing dependencies
      run: opam install -t -y . --deps-only
      working-directory: /home/opam/package
    - name: Building, installing & testing
      run: opam exec -- dune build @install @runtest
      working-directory: /home/opam/package
  fedora_32:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam@sha256:3f0a841d797b0f980129c4f6830ab3c80c28450ed2a7c62746d3383dcbe29d32
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e 37ac8ae226969d6a789f1e5eb7e3dfdf2ec9a95a
        || git fetch origin master) && git reset -q --hard 37ac8ae226969d6a789f1e5eb7e3dfdf2ec9a95a
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - name: Cloning
      run: git clone --recursive https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - name: Pinning Packages
      run: opam pin add -yn uvarint.dev './' && opam pin add -yn multihash.dev './'
        && opam pin add -yn multihash-digestif.dev './' && opam pin add -yn multicodec.dev
        './' && opam pin add -yn multiaddr.dev './'
      working-directory: /home/opam/package
    - name: Installing external dependencies
      run: opam depext -yt uvarint.dev multihash.dev multihash-digestif.dev multicodec.dev
        multiaddr.dev
      working-directory: /home/opam/package
    - name: Installing dependencies
      run: opam install -t -y . --deps-only
      working-directory: /home/opam/package
    - name: Building, installing & testing
      run: opam exec -- dune build @install @runtest
      working-directory: /home/opam/package
